stages:
  - prerequisite
  - build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_TITLE =~ /^A6RC */

variables: &global-variables
    PROJ_ROOT_DIR: /root/$CI_PROJECT_NAME
    PROJ_BUILD_DIR: /root/$CI_PROJECT_NAME/build
    GITLAB_BUILDS_DIR: /builds/$GITLAB_USER_NAME/$CI_PROJECT_NAME

default:
  image: ubuntu:cicd
  tags:
    - tagD

.ssh_agent_setup: &ssh_agent_setup
  ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    - git config --global user.email "ruixiang.huang@aylaasia.com"
    - git config --global user.name "darkerb"

pre_project:
  stage: prerequisite
  variables:
    <<: *global-variables
    VM_IPADDRESS: github.com
    GIT_STRATEGY: none
  before_script:
    - echo "$SSH_PRIVATE_KEY"
    - *ssh_agent_setup
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - export
    - echo "end of the export"
    - pwd
    - ls -a
    - cd $PROJ_ROOT_DIR
    - ls -a
    - git submodule update --init --recursive
    - cd sub_repo/Darkerb_Test_CICD
    - ls -a
    - cd ../../
    - pwd

build_test1:
  stage: build
  variables:
    <<: *global-variables
    GIT_STRATEGY: none
  before_script:
    - *ssh_agent_setup
  script:
    - pwd
    - cd $PROJ_ROOT_DIR
    - git submodule update --init --recursive
    - make
    - cp -r build $GITLAB_BUILDS_DIR
    - cd /sub_repo/Darkerb_Test_CICD
    - ls -a
    - cd $GITLAB_BUILDS_DIR/build
    - ls -a
  artifacts:
    paths:
      - build/

build_test2:
  stage: build
  script:
    - pwd

deploy-prod:
  stage: deploy
  variables:
    <<: *global-variables
    GIT_STRATEGY: none
  script:
    - pwd
    - cd build
    - ./main
