stages:
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_COMMIT_TITLE =~ /^A6RC*/

default:
  image: ubuntu:20.04

build-job:
  stage: build
  before_script:
    - echo "The commit title is $CI_COMMIT_TITLE."
    - echo "The pipeline source is $CI_PIPELINE_SOURCE."
    - echo "The commit message is $CI_COMMIT_MESSAGE."
    - echo "target branch is $CI_MERGE_REQUEST_TARGET_BRANCH_NAME."
    - export
    - echo "end of the export"
    - apt update
    - apt install -y git
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - git submodule update
    - ls -a
    - cd sub_repo/Darkerb_Test_CICD
    - ls -a
    - cd ../../
    - pwd
    - cd /
    - pwd

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
