FROM ubuntu:20.04

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y \
        python3.8 \
        pip \
    && apt-get clean \
    && pip install requests \
    && mkdir home/Hisense

ADD . home/Hisense